# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np
import random

array=np.zeros((5,5),int)
for i in range(0,5):
    for j in range(0,5):
        array[i][j]=random.randint(1,20)
print(array)
array[0:,3-1:3]=1
print(array)

[[12  3 13  8 16]
 [10  2 19  8  5]
 [ 3 17 15 20  8]
 [ 9  9 15 17  2]
 [15 16 15  5 11]]
[[12  3  1  8 16]
 [10  2  1  8  5]
 [ 3 17  1 20  8]
 [ 9  9  1 17  2]
 [15 16  1  5 11]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [28]:
array=np.zeros((4,4),int)
for i in range(0,4):
    for j in range(0,4):
        array[i][j]=random.randint(1,16)
print(array)
for i in range(0,4):
    array[i][i]=0
print(array)

[[10 13  1  9]
 [ 7 12  6  2]
 [ 4  7  7  6]
 [ 9  4  7  7]]
[[ 0 13  1  9]
 [ 7  0  6  2]
 [ 4  7  0  6]
 [ 9  4  7  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [30]:
array=np.zeros((6,6),int)
for i in range(0,6):
    for j in range(0,6):
        array[i][j]=random.randint(1,36)
sub_array=array[2:5,1:4]
print(array)
print(sub_array)


[[15 16 19 31 34 20]
 [11  6 35 30 34 11]
 [19  6 14 24 14 32]
 [ 8 19 13 27  9  5]
 [ 7 20 13 33 29 12]
 [30 11 22 32 13 14]]
[[ 6 14 24]
 [19 13 27]
 [20 13 33]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [62]:
n=5
array=np.zeros((n,n),int)
for i in range(0,n):
    for j in range(0,n):
        array[i][j]=random.randint(1,99)
print(array)
res_str=""
for i in range(0,n):
    res_str+=" "+str(array[0,i])
for i in range(1,n-1):
    res_str+=" "+str(array[i][n-1])
for i in range(1,n+1):
    res_str+=" "+str(array[n-1,-i])
for i in range(2,n):
    res_str+=" "+str(array[-i][0])
print("Border elements: ",res_str)

[[40 41 76 11 66]
 [63 60 77 77 26]
 [ 3 39  5 12 91]
 [12 44 68 72 28]
 [34 21 23 18 32]]
Border elements:   40 41 76 11 66 26 91 28 32 18 23 21 34 12 3 63


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [67]:
i_max=3
j_max=4
arr1=np.random.randint(999,size=(i_max,j_max))
arr2=np.random.randint(999,size=(i_max,j_max))
print(arr1)
print(arr2)
print("Element-wise addition:")
print(arr1+arr2)
print("Element-wise substraction:")
print(arr1-arr2)
print("Element-wise multiplication:")
print(arr1*arr2)
print("Element-wise division:")
print(arr1/arr2)

[[646 445  86 428]
 [882  67  21 802]
 [614 695 639 200]]
[[531 812 886 247]
 [607 327 716 664]
 [261 890 628 146]]
Element-wise addition:
[[1177 1257  972  675]
 [1489  394  737 1466]
 [ 875 1585 1267  346]]
Element-wise substraction:
[[ 115 -367 -800  181]
 [ 275 -260 -695  138]
 [ 353 -195   11   54]]
Element-wise multiplication:
[[343026 361340  76196 105716]
 [535374  21909  15036 532528]
 [160254 618550 401292  29200]]
Element-wise division:
[[1.2165725  0.54802956 0.09706546 1.73279352]
 [1.45304778 0.20489297 0.02932961 1.20783133]
 [2.35249042 0.78089888 1.01751592 1.36986301]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [72]:
array=np.random.randint(low=1,high=16,size=(4,4))
print(array)
array[0:1]=array[0:1]+1
print(array)
array[0:,0:1]=array[0:,0:1]+1
print(array)

[[ 4  5 11 15]
 [ 2  7 11  2]
 [10 14 12  4]
 [15 11 10 10]]
[[ 5  6 12 16]
 [ 2  7 11  2]
 [10 14 12  4]
 [15 11 10 10]]
[[ 6  6 12 16]
 [ 3  7 11  2]
 [11 14 12  4]
 [16 11 10 10]]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [81]:
array=np.random.randint(999,size=(5,))
print(array)
array_mean=array.mean()
print(array_mean)
array_median=np.median(array)
print(array_median)
array_std=array.std()
print(array_std)
array_var=array.var()
print(array_var)

[139 870 686 269 714]
535.6
686.0
280.9402783511115
78927.44


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [ ]:
array=np.random.randint(low=1,high=9,size=(3,3))
print(array)
array_mean=array.mean();array_std=array.std()
print(array_mean," ",array_std)
normalized_array=(array-array_mean)/array_std
print(normalized_array)

[[6 8 5]
 [4 7 4]
 [8 6 4]]
5.777777777777778   1.547598697464902
[[ 0.14359163  1.43591632 -0.50257071]
 [-1.14873305  0.78975397 -1.14873305]
 [ 1.43591632  0.14359163 -1.14873305]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [85]:
array=np.random.randint(0,999,(3,3))
print(array)
new_array=np.random.randint(0,999,(3,))
print(new_array)
array=array+new_array
print(array)

[[760 459 927]
 [777   0 267]
 [723 302   7]]
[473 680 356]
[[1233 1139 1283]
 [1250  680  623]
 [1196  982  363]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [86]:
array=np.random.randint(0,999,(4,4))
print(array)
new_array=np.random.randint(0,999,(4,))
print(new_array)
array=array-new_array[:,np.newaxis]
print(array)

[[452 574 511 247]
 [979 698 921 206]
 [ 87 987 424 548]
 [976  19 852 866]]
[ 63  98 110 564]
[[ 389  511  448  184]
 [ 881  600  823  108]
 [ -23  877  314  438]
 [ 412 -545  288  302]]


### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [93]:
array=np.random.randint(0,9,(3,3))
print(array)
determinant=np.linalg.det(array)
print(determinant)
inverse_matrix=np.linalg.inv(array)
print(inverse_matrix)
eigenvalues_matrix=np.linalg.eigvals(array)
print(eigenvalues_matrix)

[[3 2 3]
 [5 1 3]
 [4 1 2]]
4.000000000000001
[[-0.25 -0.25  0.75]
 [ 0.5  -1.5   1.5 ]
 [ 0.25  1.25 -1.75]]
[ 7.84867407 -1.51149862 -0.33717545]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [97]:
arr1=np.random.randint(0,9,(2,3))
arr2=np.random.randint(0,9,(3,2))
print(arr1)
print(arr2)
multi_matrix=np.linalg.matmul(arr1,arr2)
print(multi_matrix)

[[2 0 1]
 [5 3 7]]
[[8 6]
 [2 4]
 [0 3]]
[[16 15]
 [46 63]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [100]:
array=np.random.randint(1,9,(3,3))
print(array)
array=array.reshape((1,9))
print(array)
array=array.reshape(9,1)
print(array)

[[3 2 5]
 [6 2 2]
 [2 8 5]]
[[3 2 5 6 2 2 2 8 5]]
[[3]
 [2]
 [5]
 [6]
 [2]
 [2]
 [2]
 [8]
 [5]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [101]:
array=np.random.randint(1,9,(5,5))
print(array)
array=array.flatten()
print(array)
array=array.reshape((5,5))
print(array)

[[3 2 2 6 4]
 [1 6 2 6 8]
 [6 6 8 7 5]
 [2 3 5 1 8]
 [1 4 8 8 1]]
[3 2 2 6 4 1 6 2 6 8 6 6 8 7 5 2 3 5 1 8 1 4 8 8 1]
[[3 2 2 6 4]
 [1 6 2 6 8]
 [6 6 8 7 5]
 [2 3 5 1 8]
 [1 4 8 8 1]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [103]:
array=np.random.randint(1,9,(5,5))
print(array)
row_i=np.array([0,4,0,4])
col_i=np.array([0,4,4,0])
corners_array=array[row_i,col_i]
print(corners_array)

[[4 6 1 6 8]
 [5 5 7 5 1]
 [8 3 5 7 6]
 [3 8 2 4 7]
 [7 8 7 3 3]]
[4 3 8 7]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [106]:
array=np.random.randint(1,99,(4,4))
print(array)
array[array>10]=10
print(array)

[[35 77 47 18]
 [69 87  4 53]
 [49 76 27 68]
 [78 19 41 77]]
[[10 10 10 10]
 [10 10  4 10]
 [10 10 10 10]
 [10 10 10 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [116]:
dtype=[('name','U10'),('age','int'),('weight','float')]
data=np.array([('A',55,50.0),('B',24,137.0),('C',73,30.0)],dtype=dtype)
print(data)
sorted_array=np.sort(data,order='age')
print(sorted_array)


[('A', 55,  50.) ('B', 24, 137.) ('C', 73,  30.)]
[('B', 24, 137.) ('A', 55,  50.) ('C', 73,  30.)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [124]:
dtype=[('x','int'),('y','int')]
points=np.array([(0,0),(4,4),(0,4)],dtype=dtype)
print(points)
distance=np.sqrt((data['x'][:,np.newaxis]-data['x'])**2+(data['y'][:,np.newaxis]-data['y'])**2)
print(distance)

[(0, 0) (4, 4) (0, 4)]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [137]:
array=np.random.randint(0,20,(4,4))
print(array)
masked_array=np.ma.masked_greater(array,10)
print(masked_array)
summa=masked_array.sum()
print(summa)

[[11  0  9 19]
 [ 6  4  6  2]
 [ 7  1  2 13]
 [15  7  2 12]]
[[-- 0 9 --]
 [6 4 6 2]
 [7 1 2 --]
 [-- 7 2 --]]
46


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [11]:
array=np.random.randint(0,20,(3,3))
print(array)
masked_array=np.ma.masked_array(array,mask=np.eye(3),fill_value=-999)
print(masked_array)
filled_array=masked_array.filled(fill_value=np.mean(masked_array))
print(filled_array)

[[11  7 12]
 [ 1  5  9]
 [13  7 16]]
[[-- 7 12]
 [1 -- 9]
 [13 7 --]]
[[ 8  7 12]
 [ 1  8  9]
 [13  7  8]]
